//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Property_Id { get; set; }
        public string PropertyName { get; set; }
        public double Price { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public int PropertyType_Id { get; set; }
        public int Agent_id { get; set; }
        public string PropertyImage { get; set; }
        public string FirstImage { get; set; }
        public string SecondImage { get; set; }
        public string ThirdImage { get; set; }
        public int PropertySize { get; set; }
        public int FloorNo { get; set; }
        public int BedRoom { get; set; }
        public int DiningSpace { get; set; }
        public int LivingRoom_ { get; set; }
        public int Balconies { get; set; }
        public int AttachedBath { get; set; }
        public int CommonBath { get; set; }
    
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual PropertyType PropertyType { get; set; }
    }

    public enum city
    {
        Dhaka,
        Chattagram
    }

    public enum area
    {


        Agargaon,
        Banani,
        Bashundhara,
        Banasree,
        Baridhara,
        Cantonmentarea,
        Gulshan,
        Badda,
        Khilgaon,
        Dhanmondi,
        Mohakhali,
        Dakshinkhan,
        Bawnia,
        Khilkhet,
        Tejgaon,
        Farmgate,
        Mohammadpur,
        Rampura,
        ZakirHossainRoad,
        Ramna,
        Motijheel,
        Shahbagh,
        ShereBanglaNagar,
        Mirpur,
        Pallabi,
        Kazipara,
        Kafrul,
        Uttara,
        Uttarkhan

    }
    public enum Status
    {
        New,
        Used
    }
    public enum purpose
    {
        Rent,
        Sale
    }

}
